version: "3.9"

services:
  rusty_sandbox:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rusty_sandbox_dev
    privileged: true
    volumes:
      - .:/app
    working_dir: /app
    command: cargo run
    stdin_open: true
    tty: true
