FROM debian:latest

# install necessary packages and rust
# also install all the language that 
# we want to support
RUN apt update && apt install -y \
    curl build-essential python3 \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && . "$HOME/.cargo/env" \
    && rustup default stable

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY . .

RUN cargo build --release

CMD ["cargo", "run"]